### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by mful** [mtarnovan/ruby_pg_cdc#1]
Hello — would be interested in using this library, but am unsure how this code is licensed. 

Github's guide to licensing: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

MIT license would be the easiest, if you are comfortable with allowing folks to "do whatever they want" with the library.

**Comment by mtarnovan** [comment]
Hi! 

As this was more of an experiment/learning opportunity, I didn't think about that. If you think it's useful, sure.

**Comment by mful** [comment]
Amazing, thanks so much :)

**Comment by mful** [comment]
Also, great work on the library!
